# Generated by Django 3.2.16 on 2025-04-24 09:30

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Card',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question', models.TextField(max_length=256, verbose_name='Вопрос')),
                ('right_answer', models.TextField(max_length=100, verbose_name='Правильный ответ')),
                ('answer1', models.TextField(max_length=100, verbose_name='Неверный ответ 3')),
            ],
            options={
                'verbose_name': 'карточка вопроса',
                'verbose_name_plural': 'Карточки вопросов',
                'ordering': ('id',),
            },
        ),
    ]
