# Generated by Django 3.2.16 on 2025-04-24 09:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='card',
            name='answer2',
            field=models.TextField(default=None, max_length=100, verbose_name='Неверный ответ 2'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='card',
            name='answer3',
            field=models.TextField(default=None, max_length=100, verbose_name='Неверный ответ 3'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='card',
            name='answer1',
            field=models.TextField(max_length=100, verbose_name='Неверный ответ 1'),
        ),
    ]
