# Generated by Django 3.2.16 on 2025-04-24 09:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_auto_20250424_1231'),
    ]

    operations = [
        migrations.CreateModel(
            name='IFile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('value', models.FileField(upload_to='files/', verbose_name='Файл')),
            ],
        ),
    ]
