# Generated by Django 3.2.16 on 2025-04-24 10:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_ifile'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='ifile',
            options={'ordering': ('id',), 'verbose_name': 'файл с вопросами', 'verbose_name_plural': 'Файлы'},
        ),
    ]
